### PR TITLE
Add .gitignore with standard Xcode/OS X ignore list

### PR DESCRIPTION
**Pull request by phatblat**
_You must ignore the .DS_Store_
_Else annoy phatblat evermore_

### CODE REVIEW

**Comment by analogcode** [comment]
🤓👍

**Comment by phatblat** [comment]
🐦🚫👍🏻

**Comment by Jxrgxn** [comment]
@phatblat What's the reason for ignoring the .DS_Store? Is it because it is a file containing information specific to a machine?

**Comment by phatblat** [comment]
It's mostly because the file has nothing to do with the code that is being tracked in git. It contains custom attributes set on the containing folder in the Finder. Unless those custom attributes are relevant to the code, that file is just noise. Additionally, if the file is not ignored and gets checked in unintentionally and later two devs each decide to put a pretty custom icon on the folder, then you could end up with a merge conflict on a binary file. 

https://en.m.wikipedia.org/wiki/.DS_Store

**Pull request merged**
